services:
  postgres:
    container_name: chat-database
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE__DATABASE}
      - POSTGRES_USER=${DATABASE__USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
    ports:
      - "${DATABASE__PORT}:5432"
    env_file:
      - .env
    restart: always

  app:
    container_name: chat-app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
