"""Initial migration

Revision ID: ce7efb557132
Revises:
Create Date: 2025-04-13 04:00:57.256071

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce7efb557132"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("chat_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "chat_type",
            sa.Enum("group", "personal", name="chat_type_entry"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_index(op.f("ix_chats_name"), "chats", ["name"], unique=False)
    op.create_table(
        "user_accounts",
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_accounts_email"), "user_accounts", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_user_accounts_name"), "user_accounts", ["name"], unique=False
    )
    op.create_table(
        "groups",
        sa.Column("group_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("creator_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user_accounts.user_id"],
        ),
        sa.PrimaryKeyConstraint("group_id"),
    )
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=False)
    op.create_table(
        "messages",
        sa.Column("message_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("chat_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("sender_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user_accounts.user_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_table(
        "group_users",
        sa.Column("group_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_accounts.user_id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_users")
    op.drop_table("messages")
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_user_accounts_name"), table_name="user_accounts")
    op.drop_index(op.f("ix_user_accounts_email"), table_name="user_accounts")
    op.drop_table("user_accounts")
    op.drop_index(op.f("ix_chats_name"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
